In [1]:
import torch
from torch import nn, tensor

In [2]:
X_train = [tensor([ 8913,  7761,  4515, 12954,  6169,  7128, 11620,   942,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]),
 tensor([16666, 13080, 14772, 18070,  1735, 20429, 18070, 12314, 15726, 18070,
         11215,  7761,  1464, 12954, 14706,  1595,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]),
 tensor([ 4497, 11093,   420,  3083,  2777,  7050, 14586, 20132,  6349,  5997,
         12855,  1311, 12577,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]),
 tensor([ 7196, 15591,  7421,  2300, 10054,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0])]

input_ids = torch.stack(X_train)
input_ids.size()

torch.Size([4, 30])

In [3]:
import numpy as np
X_train = np.array([tensor.numpy() for tensor in input_ids])
X_train

array([[ 8913,  7761,  4515, 12954,  6169,  7128, 11620,   942,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0],
       [16666, 13080, 14772, 18070,  1735, 20429, 18070, 12314, 15726,
        18070, 11215,  7761,  1464, 12954, 14706,  1595,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0],
       [ 4497, 11093,   420,  3083,  2777,  7050, 14586, 20132,  6349,
         5997, 12855,  1311, 12577,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0],
       [ 7196, 15591,  7421,  2300, 10054,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0]], dtype=int64)

In [4]:
X_train = torch.LongTensor(X_train).to("cuda")
X_train.ndim, X_train.shape

(2, torch.Size([4, 30]))

In [5]:
X_train  = np.squeeze(X_train)
X_train.ndim
X_train

tensor([[ 8913,  7761,  4515, 12954,  6169,  7128, 11620,   942,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [16666, 13080, 14772, 18070,  1735, 20429, 18070, 12314, 15726, 18070,
         11215,  7761,  1464, 12954, 14706,  1595,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 4497, 11093,   420,  3083,  2777,  7050, 14586, 20132,  6349,  5997,
         12855,  1311, 12577,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 7196, 15591,  7421,  2300, 10054,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')

In [21]:
Y_train = tensor([[0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]).to("cuda")
Y_train

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], device='cuda:0')

In [6]:
embedding_1 = nn.Embedding(20430,5).to("cuda")
embedding_1(X_train).mean().backward()
embedding_1.weight

Parameter containing:
tensor([[-1.5623,  0.3307, -1.7375, -0.6516,  0.6286],
        [-0.3498,  1.2804, -1.1967,  0.7937, -2.5152],
        [ 0.5925,  0.8923,  0.1275,  0.1657, -1.6927],
        ...,
        [-1.1267, -0.7866, -0.7257, -0.7439,  0.9918],
        [ 0.5385, -0.9795, -1.0433, -1.1132,  1.3873],
        [-0.2853,  0.1684,  0.3318,  0.4403,  0.6071]], device='cuda:0',
       requires_grad=True)

In [7]:
embedding_2 = nn.Embedding(20430,30).to("cuda")
embedding_2(X_train).mean().backward()
embedding_2.weight

Parameter containing:
tensor([[-0.4653, -0.1402, -0.5111,  ..., -0.4226, -0.4358,  0.6931],
        [-1.1975, -1.1978, -1.3791,  ...,  0.8466, -0.9747, -0.3541],
        [ 1.0532, -1.6744,  1.5458,  ..., -1.4225,  0.4158, -1.7623],
        ...,
        [ 0.9673, -1.0869, -0.2256,  ..., -0.5339,  0.2311,  1.0115],
        [-1.4787,  2.1059,  0.4451,  ...,  0.0455, -1.5949,  1.0055],
        [-1.4242, -0.0604, -0.2198,  ...,  1.6808,  0.2180, -1.3261]],
       device='cuda:0', requires_grad=True)

In [16]:
class BLSTM(nn.Module):
   def __init__(self):
    super(BLSTM,self).__init__()
    self.Embeddings = nn.Embedding(20430,100)
    self.LSTM = nn.LSTM(100,128,bidirectional=True)
    self.fc = nn.Linear(128*2,3)
    self.dropout = nn.Dropout(0.5)
    self.tanh = nn.Tanh()

   def forward(self,X):
    embed = self.Embeddings(X)
    output,(hidden,cell) = self.LSTM(embed)
    last_hidden = output[:, -1,:]
    print(last_hidden)
    logits = self.fc(self.dropout(last_hidden))
    return self.tanh(logits)
    

model = BLSTM()

In [23]:
from torch.optim import Adam
import torch.nn.functional as F


epochs = 5
lr = 3e-5
save_path = "./Output/samplemodel.pth"
model.to("cuda")


optimizer = Adam(model.parameters(),lr = lr)

criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):
    model.train()
    train_loss = 0
    optimizer.zero_grad()
    logits = model(X_train)
    loss = criterion(logits,Y_train)
    loss.backward()

    optimizer.step()
    train_loss += loss.item()

    print(f"Epoch : {epoch+1}/ {epoch}")

torch.save(model.state_dict(),save_path)



tensor([[-0.2276,  0.0593,  0.0443,  ...,  0.0228,  0.1420, -0.1686],
        [-0.3204,  0.0834,  0.0643,  ...,  0.0131,  0.1222, -0.1395],
        [-0.3600,  0.0907,  0.0751,  ...,  0.0015,  0.0923, -0.1034],
        [-0.3776,  0.0909,  0.0815,  ..., -0.0079,  0.0494, -0.0587]],
       device='cuda:0', grad_fn=<SliceBackward0>)
Epoch : 1/ 0
tensor([[-0.2269,  0.0586,  0.0449,  ...,  0.0237,  0.1437, -0.1713],
        [-0.3194,  0.0820,  0.0651,  ...,  0.0139,  0.1235, -0.1417],
        [-0.3588,  0.0887,  0.0761,  ...,  0.0021,  0.0932, -0.1049],
        [-0.3764,  0.0885,  0.0825,  ..., -0.0075,  0.0498, -0.0594]],
       device='cuda:0', grad_fn=<SliceBackward0>)
Epoch : 2/ 1
tensor([[-0.2263,  0.0579,  0.0445,  ...,  0.0237,  0.1433, -0.1724],
        [-0.3184,  0.0808,  0.0644,  ...,  0.0140,  0.1231, -0.1426],
        [-0.3576,  0.0870,  0.0751,  ...,  0.0021,  0.0928, -0.1055],
        [-0.3751,  0.0865,  0.0812,  ..., -0.0075,  0.0495, -0.0597]],
       device='cuda:0', grad_fn

In [35]:
import torch
import numpy as np

class ALSAPredictHard(nn.Module):
    def __init__(self):
        super(ALSAPredictHard,self).__init__()
        self.Embeddings = nn.Embedding(20430,100)
        self.LSTM = nn.LSTM(100,128,num_layers=1,batch_first=True,bidirectional=True)
        self.fc = nn.Linear(128*2,3)
        self.dropout = nn.Dropout(0.5)
        self.tanh = nn.Tanh()

    def forward(self,X):
        embed = self.Embeddings(X)
        output , (hidden,cell) = self.LSTM(embed)
        last_hidden = output[:,-1,:]
        logits = self.fc(self.dropout(last_hidden))
        return self.tanh(logits)
    

model = ALSAPredictHard()
model.load_state_dict(torch.load("D:/FinalYearProj/backend/Output/samplemodel.pth"))
model.to("cuda")
model.eval()

def prepare_input(data):
    return torch.tensor(data).unsqueeze(0).to('cuda')


data_X_test = np.array([ 8913,  7761,  4515, 12954,  6169,  7128, 11620,   942,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0])

X_test = prepare_input(data_X_test)
print(X_test.ndim)

with torch.no_grad():
    logits = model(X_test)

predictions = torch.argmax(logits,dim=1)
predictions

2


C:\Users\ABINAYA SANKAR M\AppData\Local\Temp\ipykernel_13900\944173087.py:22: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("D:/FinalYearPro

tensor([1], device='cuda:0')